"""
VCPulse Stock Return Validation v0.9

Purpose
-------
Test whether VCP radar stocks inside an early high-Setup theme outperform
ordinary VCP radar stocks.

Frozen signal definition:
  Theme event = guarded Setup >= 70 AND Heat < 45
  Cooldown = 5 trading days per theme

Stock cohort:
  On each independent theme event day, take that theme's VCP radar members.
  Compare with same-day VCP radar stocks whose canonical themes are NOT in an
  active high-Setup/low-Heat event.

Forward metrics:
  +5 / +10 / +20 close-to-close return
  maximum favorable excursion (MFE)
  maximum adverse excursion (MAE)

No production model or score weights are changed.
"""

from __future__ import annotations
import argparse, json
from pathlib import Path
from collections import defaultdict
import pandas as pd

def theme_map(day):
    return {x["theme"]: x for x in day.get("themes", [])}

def stock_theme_set(detail):
    return {
        m.get("canonicalTheme")
        for m in detail.get("canonicalMemberships", [])
        if m.get("effectiveWeight", 0) > 0 and m.get("canonicalTheme")
    }

def median(vals):
    if not vals: return None
    s=sorted(vals); n=len(s)
    return s[n//2] if n%2 else (s[n//2-1]+s[n//2])/2

def summarize_rows(rows, horizons):
    out={"n":len(rows)}
    for h in horizons:
        rs=[r[f"ret{h}"] for r in rows if r.get(f"ret{h}") is not None]
        mf=[r[f"mfe{h}"] for r in rows if r.get(f"mfe{h}") is not None]
        ma=[r[f"mae{h}"] for r in rows if r.get(f"mae{h}") is not None]
        out[str(h)]={
            "n":len(rs),
            "avgReturnPct":round(sum(rs)/len(rs),2) if rs else None,
            "medianReturnPct":round(median(rs),2) if rs else None,
            "positivePct":round(sum(x>0 for x in rs)/len(rs)*100,1) if rs else None,
            "avgMfePct":round(sum(mf)/len(mf),2) if mf else None,
            "avgMaePct":round(sum(ma)/len(ma),2) if ma else None,
        }
    return out

def main():
    ap=argparse.ArgumentParser()
    ap.add_argument("--daily", required=True)
    ap.add_argument("--cache-dir", required=True)
    ap.add_argument("--out-dir", default="stock_return_validation_output")
    ap.add_argument("--setup-threshold", type=float, default=70)
    ap.add_argument("--heat-max", type=float, default=45)
    ap.add_argument("--cooldown", type=int, default=5)
    args=ap.parse_args()

    daily=json.loads(Path(args.daily).read_text(encoding="utf-8"))
    maps=[theme_map(d) for d in daily]
    horizons=(5,10,20)

    # Independent theme events using same frozen v0.7 rule.
    events=[]
    last_event={}
    for i,day in enumerate(daily):
        for theme,x in maps[i].items():
            if x.get("setup",0)<args.setup_threshold or x.get("heat",0)>=args.heat_max:
                continue
            if theme in last_event and i-last_event[theme] <= args.cooldown:
                continue
            last_event[theme]=i
            events.append((i,day["date"],theme,x))

    # Price cache generated by historical runner.
    price={}
    for p in Path(args.cache_dir).glob("*.csv"):
        code=p.stem
        try:
            df=pd.read_csv(p,parse_dates=["Date"]).set_index("Date").sort_index()
            price[code]=df
        except Exception:
            pass

    def forward_metrics(code,date0):
        df=price.get(code)
        if df is None or df.empty: return {}
        ts=pd.Timestamp(date0)
        if ts not in df.index: return {}
        loc=df.index.get_loc(ts)
        if not isinstance(loc,int): return {}
        p0=float(df.iloc[loc]["Close"])
        out={}
        for h in horizons:
            if loc+h>=len(df):
                out[f"ret{h}"]=out[f"mfe{h}"]=out[f"mae{h}"]=None
                continue
            win=df.iloc[loc+1:loc+h+1]
            ph=float(df.iloc[loc+h]["Close"])
            out[f"ret{h}"]=(ph/p0-1)*100
            out[f"mfe{h}"]=(float(win["High"].max())/p0-1)*100
            out[f"mae{h}"]=(float(win["Low"].min())/p0-1)*100
        return out

    signal_rows=[]
    control_rows=[]
    event_records=[]

    for i,date0,theme,x in events:
        details=daily[i].get("radarDetails",[])
        signal_codes=[]
        for s in details:
            if theme in stock_theme_set(s):
                signal_codes.append(s["code"])

        # Same-day controls: radar stocks with no membership in ANY currently
        # high-Setup/low-Heat theme on that day.
        active_themes={
            t for t,y in maps[i].items()
            if y.get("setup",0)>=args.setup_threshold and y.get("heat",0)<args.heat_max
        }
        control_codes=[]
        for s in details:
            if stock_theme_set(s).isdisjoint(active_themes):
                control_codes.append(s["code"])

        for cohort,codes,target in (
            ("signal",signal_codes,signal_rows),
            ("control",control_codes,control_rows),
        ):
            for code in sorted(set(codes)):
                row={"eventDate":date0,"eventTheme":theme,"code":code,"cohort":cohort}
                row.update(forward_metrics(code,date0))
                target.append(row)

        event_records.append({
            "date":date0,"theme":theme,"setup":x.get("setup"),"heat":x.get("heat"),
            "signalStocks":sorted(set(signal_codes)),
            "controlStocks":sorted(set(control_codes))
        })

    summary={
        "version":"v0.9-stock-return-validation",
        "modelChanged":False,
        "eventCount":len(events),
        "signal":summarize_rows(signal_rows,horizons),
        "control":summarize_rows(control_rows,horizons),
        "differenceSignalMinusControl":{},
        "limitations":[
            "This is observational historical validation, not a trading simulation.",
            "The same stock may appear in multiple independent events over time.",
            "Controls are same-day VCP radar stocks, but are not matched on sector, market cap, liquidity, or VCP score.",
            "Returns exclude fees, taxes, slippage, dividends, and execution constraints.",
            "Current theme membership is used historically, which can create survivorship/classification bias.",
        ]
    }
    for h in horizons:
        a=summary["signal"][str(h)]
        b=summary["control"][str(h)]
        summary["differenceSignalMinusControl"][str(h)]={
            "avgReturnPctPoints":round(a["avgReturnPct"]-b["avgReturnPct"],2) if a["avgReturnPct"] is not None and b["avgReturnPct"] is not None else None,
            "medianReturnPctPoints":round(a["medianReturnPct"]-b["medianReturnPct"],2) if a["medianReturnPct"] is not None and b["medianReturnPct"] is not None else None,
            "positiveRatePctPoints":round(a["positivePct"]-b["positivePct"],1) if a["positivePct"] is not None and b["positivePct"] is not None else None,
        }

    out=Path(args.out_dir); out.mkdir(parents=True,exist_ok=True)
    (out/"stock_return_events.json").write_text(json.dumps(event_records,ensure_ascii=False,indent=2),encoding="utf-8")
    (out/"stock_return_rows.json").write_text(json.dumps({"signal":signal_rows,"control":control_rows},ensure_ascii=False,indent=2),encoding="utf-8")
    (out/"stock_return_summary.json").write_text(json.dumps(summary,ensure_ascii=False,indent=2),encoding="utf-8")
    print(json.dumps(summary,ensure_ascii=False,indent=2))

if __name__=="__main__":
    main()
